### ISSUE TITLE
org.jfree.chart.axis.CategoryAxis3D Not found

### ISSUE THREAD

**Issue by MarchLiu** [wookietreiber/scala-chart#33]
code as below:
```scala
import scalax.chart.api._

val chart = BarChart(data)
```
will throw:
```
java.lang.NoClassDefFoundError: org/jfree/chart/axis/CategoryAxis3D
  at scalax.chart.api$.BarChart$lzycompute$1(api.scala:7)
  at scalax.chart.api$.BarChart(api.scala:7)
  ... 36 elided
Caused by: java.lang.ClassNotFoundException: org.jfree.chart.axis.CategoryAxis3D
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  ... 38 more
```
sbt as :
libraryDependencies += "com.github.wookietreiber" %% "scala-chart" % "0.5.1"

**Comment by MarchLiu** [comment]
I make a explicit library dependency for jfreechart as :
```scala
libraryDependencies +="jfree" % "jfreechart" % "1.0.13"
libraryDependencies += "com.github.wookietreiber" %% "scala-chart" % "0.5.1"
```
Then it worked.
